export const FETCHING_INVESTMENT = "FETCHING_INVESTMENT";
// export const FETCHED_ALL_INVESTMENT = "FETCHED_ALL_INVESTMENT";
export const CLEAR_INVESTMENT_ERROR = "CLEAR_INVESTMENT_ERROR";
export const FETCH_INVESTMENT_FAILED = "FETCH_INVESTMENT_FAILED";

export const FETCHING_INVESTMENT_DETAIL = "FETCHING_INVESTMENT_DETAIL";
export const FETCH_INVESTMENT_DETAIL_FAILED = "FETCH_INVESTMENT_DETAIL_FAILED";
export const CLEAR_INVESTMENT_DETAIL_ERROR = "CLEAR_INVESTMENT_DETAIL_ERROR";
export const CREATE_INVESTMENT_CLEAR = "CREATE_INVESTMENT_CLEAR";
export const CREATE_INVESTMENT = "CREATE_INVESTMENT";
export const SHOW_INVESTMENT_OVERVIEW = "SHOW_INVESTMENT_OVERVIEW";
export const CLEAR_INVESTMENT_OVERVIEW = "CLEAR_INVESTMENT_OVERVIEW";

export const FETCH_INVESTMENT_COMPLETED = "FETCH_INVESTMENT_COMPLETED";
export const GET_SELECTED_TYPE = "GET_SELECTED_TYPE";
export const RESET_SELECTED_TYPE = "RESET_SELECTED_TYPE";

export const FETCHING_SEARCH_INVESTMENT = "FETCHING_SEARCH_INVESTMENT";
export const FETCHED_SEARCH_INVESTMENT = "FETCHED_SEARCH_INVESTMENT";
export const RESET_SEARCH_INVESTMENT = "RESET_SEARCH_INVESTMENT";

export const FETCHED_ACTIVE_FIXED_INVESTMENT_DETAIL =
  "FETCHED_ACTIVE_FIXED_INVESTMENT_DETAIL";
