export const SEARCHING_MESSAGE = "SEARCHING_MESSAGE";
export const SEARCH_MESSAGE_COMPLETE = "SEARCH_MESSAGE_COMPLETE";
export const SEARCH_MESSAGE_FAILED = "SEARCH_MESSAGE_FAILED";
export const SELECT_MESSAGE = "SELECT_MESSAGE";
export const CLEAR_SELECTED_MESSAGE = "CLEAR_SELECTED_MESSAGE";

export const SEARCHING_INVESTMENT = "SEARCHING_INVESTMENT";
export const SEARCH_INVESTMENT_COMPLETE = "SEARCH_INVESTMENT_COMPLETE";
export const SEARCH_INVESTMENT_FAILED = "SEARCH_MESSAGE_FAILED";
export const SELECT_INVESTMENT = "SELECT_INVESTMENT";
export const CLEAR_SELECTED_INVESTMENT = "CLEAR_SELECTED_INVESTMENT";