export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"
export const LOGGING_IN = "LOGGING_IN"
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGOUT = "LOGOUT";
export const CLEAR_LOGIN_ERROR = "CLEAR_LOGIN_ERROR";


export const REGISTERING = "REGISTERING"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const REGISTER_COMPLETED = "REGISTER_COMPLETED";
export const REGISTER_RESET = "REGISTER_RESET";