export const FETCHING_CHANGE_PWD = "FETCHING_CHANGE_PWD";
export const CHANGE_PWD_ERROR = "CHANGE_PWD_ERROR";
export const CHANGE_PWD_COMPLETE = "CHANGE_PWD_COMPLETE";

export const FETCHING_TRANSACTION_PIN = "FETCHING_TRANSACTION_PIN";
export const TRANSACTION_PIN_ERROR = "TRANSACTION_PIN_ERROR";
export const TRANSACTION_PIN_COMPLETE = "TRANSACTION_PIN_COMPLETE";

export const FETCHING_SECURITY_QUES = "FETCHING_SECURITY_QUES";
export const SECURITY_QUES_ERROR = "SECURITY_QUES_ERROR";
export const SECURITY_QUES_COMPLETE = "SECURITY_QUES_COMPLETE";

export const FETCHING_ALL_INVEST_COUNT = "FETCHING_ALL_INVEST_COUNT";
export const FETCHED_ALL_INVEST_COUNT = "FETCHED_ALL_INVEST_COUNT";
export const FETCHED_ALL_INVEST_ERROR = "FETCHED_ALL_INVEST_ERROR";

export const FETCHING_ALL_ACTIVE_INVEST = "FETCHING_ALL_ACTIVE_INVEST";
export const FETCHING_ALL_FUTURE_INVEST = "FETCHING_ALL_FUTURE_INVEST";
export const FETCHING_ALL_COMPLETED_INVEST = "FETCHING_ALL_COMPLETED_INVEST";
export const FETCHED_ALL_ACTIVE_INVEST = "FETCHED_ALL_ACTIVE_INVEST";
export const FETCHED_ALL_FUTURE_INVEST = "FETCHED_ALL_FUTURE_INVEST";
export const FETCHED_ALL_COMPLETED_INVEST = "FETCHED_ALL_COMPLETED_INVEST";
